version: "3.8"

services:
  app:
    image: ghcr.io/ly921002/x-cf:SOCKS5
    container_name: x-cf
    restart: unless-stopped
    network_mode: host     # 使用宿主机网络
    environment:
      UUID: 
      ARGO_AUTH: ey
      ARGO_DOMAIN: domain
      ARGO_PORT: 8001
      CFIP_v4: ip.sb
      SOCKS_IP: 你的代理IP
      SOCKS_PORT: 端口
      SOCKS_USER: 账号
      SOCKS_PASS: 密码
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
