version: "3.8"

services:
  app:
    image: ghcr.io/ly921002/x-cf:latest
    container_name: x-cf-argo
    restart: unless-stopped
    network_mode: host
    environment:
      UUID: ""
      ARGO_AUTH: "ey..."
      ARGO_DOMAIN: "example.trycloudflare.com"
      ARGO_PORT: 8001
      XHTTP_PATH_BASE: "/api/v1"
      XHTTP_PATH_LEN: 8
      CFIP: "www.visa.cn"
      CFPORT: 443
