version: "3.8"

services:
  app:
    image: ghcr.io/ly921002/x-cf:cdn
    container_name: x-cf-cdn
    restart: unless-stopped
    network_mode: host
    environment:
      UUID: ""
      DOMAIN: "example.com"
      XRAY_PORT: 8001
      CERT_FILE: "/cert/cert.pem"
      KEY_FILE: "/cert/key.key"
      CFIP: "www.visa.cn"
      CFPORT: 443
      XHTTP_PATH_BASE: "/api/v1"
      XHTTP_PATH_LEN: 8
    volumes:
      - ./cert:/cert:ro
